### ISSUE TITLE
Add some OpenCV filters to menu

### ISSUE THREAD

**Issue by ojgarciab** [JdeRobot4Android/AndroidOpenCVDemo#16]
It's time to do a little menu and select between several filters.

I thought that is a good idea maintain an input and output image (left and right ones) to see the differences.

I'll implement it tonight or tomorrow. Send me a hangouts message if you want to implement it.

**Comment by gsssrao** [comment]
By the way, could me tell me the list of all the filters that you would like to implement. I will work on it tomorrow. At present there are gray, canny and sobel. We can also add threshold for canny.

**Comment by ojgarciab** [comment]
Take a look at:
- https://github.com/ojgarciab/JdeRobot/tree/Fix_27/src/stable/components/opencvdemo

In special this file:
- https://github.com/ojgarciab/JdeRobot/blob/Fix_27/src/stable/components/opencvdemo/viewer.cpp

Viewer::ApplySelection does the job of calling selected filters: https://github.com/ojgarciab/JdeRobot/blob/Fix_27/src/stable/components/opencvdemo/viewer.cpp#L915

**Comment by gsssrao** [comment]
Ok.

**Comment by gsssrao** [comment]
I have added a little menu for selecting between filters. You get access it by swiping right from the left corner. Also added support for Laplacian, Color and Harris. I am working on others at the moment. Could you please have a look at it?

**Comment by gsssrao** [comment]
I think we can close this issue (All the filters have been added except the convolution one). Next part would be the adding of seek bars which can be done on a different issue.
